name: CI

on:
  workflow_dispatch:
    inputs:
      brands:
        required: true
        type: string
        default: 'Capital,Capital Xtra'
      version:
        name: Version number, if not specified uses existing version number
        type: string
        default: '1'
  
jobs:
  tag_build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.version }}    

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create tag ${{ github.event.inputs.version }}
      run: |
        date >> asd
        git config user.email "jenkins@ci.local"
        git config user.name "Jenkins"
        git add .
        git commit -m "Asd"
        git push origin head
        git tag ios-${{ github.event.inputs.version }}
        git push origin ios-${{ github.event.inputs.version }}

  generate_matrix:
    runs-on: ubuntu-latest
    needs:
      - tag_build
    outputs:
      brands: ${{ steps.generate-matrix-step.outputs.brands }}

    steps:
      - name: Generate Matrix
        id: generate-matrix-step
        run: |
          BRANDS=$(echo "${{ github.event.inputs.brands }}" | perl -p -e "s/,/\",\"/g" | sed 's/^/[\"/g' | sed 's/$/\"]/g')
          echo ${BRANDS}
          echo ::set-output name=brands::${BRANDS}

  my_matrix:
    runs-on: ubuntu-latest
    needs:
      - generate_matrix
    strategy:
      matrix:
        brand: ${{ fromJSON(needs.generate_matrix.outputs.brands) }}
    steps:
      - name: Matrix => (${{ matrix.brand }})
        run: echo ${{ matrix.brand }}
